engines:
  checkstyle:
    enabled: true 
    config: 'config/checkstyle/checkstyle.xml'
    channel: 'beta'
  
exclude_paths: [
  "build/"
  "mediation/src/test/"
  "mediation.adaters/"
  "mediation.demo/src/main/java/net/pubnative/mediation/demo/"
]