engines:
  pmd:
      enabled: true
      config: 'config/pmd/pmd.xml'
      channel: 'beta'
ratings:
   paths:  [
   "**.java"
   ]
exclude_paths: [
  "build/",
  "**/test/",
  "**/exceptions/",
  "mediation.adaters/",
  "**/demo/",
  "**/model/"
]