engines:
  checkstyle:
    enabled: true 
    config: 'config/checkstyle/checkstyle.xml'
    channel: 'beta'

exclude_paths: [
  "build/",
  "**/test/",
  "mediation.adaters/",
  "**/demo/",
  "**/model/"
]