engines:
  checkstyle:
    enabled: true 
    config: 'config/checkstyle/checkstyle.xml'
    channel: 'beta'
ratings:
   paths:  [
   "**.java"
   ]
exclude_paths: [
  "build/",
  "**/test/",
  "mediation.adaters/",
  "**/demo/",
  "**/model/"
]